require:
  - rubocop-performance
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/redirect-uri.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
